def f1(request):
	return Httpresponse(index.....)
def f2(request):
        return Httpresponse(index.....)
def f3(request):
        return Httpresponse(index.....)
def f4(request):
        return Httpresponse(index.....4)
def f5(request):
        return Httpresponse(index.....5)
